export const cloudinaryName = "dbzh1g3j0";
export const sliderData = [
  {
    title: "Biogaran",
    content: "Spot publicitaire de marque pour la CAN 2024",
    image: "agency_africa/thumbnails/biogaran_can24",
    video: "agency_africa/videos/biogaran_can24_void",
    id: "biogaran",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "Axa Maroc",
    content: "Campagne publicitaire pour le numéro court 2992",
    image: "agency_africa/thumbnails/axa_2992",
    video: "agency_africa/videos/axa_ar",
    id: "axa-maroc",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "#ClapClapTour21",
    content: "La campagne d'employee advocacy du Groupe ELSAN",
    image: "agency_africa/thumbnails/clapclap_tour21_elsan",
    video: "agency_africa/videos/case_elsan_clapclaptour21_long",
    id: "clapclap-tour-21",
    isAward: true,
    isStrategiesGrandPrix: false,
  },
  {
    title: "Pernod Ricard",
    content: "Le premier rapport annuel 100% vidéo",
    image: "agency_africa/thumbnails/pernod_ricard_rapport_annuel",
    video: "agency_africa/videos/pernod_ricard_video_digital",
    id: "pernod-ricard",
    isAward: false,
    isStrategiesGrandPrix: true,
  },
  {
    title: "Accor",
    content:
      "Vidéo de prospective sur l'intelligence artificielle dans le Groupe",
    image: "agency_africa/thumbnails/accor_ai",
    video: "agency_africa/videos/wip_en_3mn",
    id: "accor",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "Elsan 20 ans",
    content:
      "Vidéo en motion design pour les célébrer l'anniversaire du Groupe",
    image: "agency_africa/thumbnails/elsan_20_ans",
    video: "agency_africa/videos/film20ans_edit09_60is",
    id: "elsan-20-ans",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "Africa Bright",
    content: "Film institutionnel d'un groupe bancaire panafricain indépendant",
    image: "agency_africa/thumbnails/africa_bright_film",
    video: "agency_africa/videos/film_instit_africa_bright",
    id: "africa-bright",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "Alcatel",
    content:
      "Campagne publicitaire mondiale de lancement du smartphone OneTouch",
    image: "agency_africa/thumbnails/alcatel_one_touch",
    video: "agency_africa/videos/alcatel_idol4_30",
    id: "alcatel",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "AttijariCIB",
    content:
      "Vidéo de présentation portail d'Attijariwafa bank Corporate & Investment Banking",
    image: "agency_africa/thumbnails/awb_cib",
    video: "agency_africa/videos/montage_cib_f3",
    id: "attijari-cib",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "#ShowYourFreshFace",
    content: "Campagne de marque pan Européenne pour le Groupe Mondelez",
    image: "agency_africa/thumbnails/show_your_fresh_face_mondelez",
    video: "agency_africa/videos/mondelez_1",
    id: "show-your-fresh-face",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "CDG Capital",
    content:
      "Vidéo institutionnelle pour la banque de financement et d'investissement Marocaine",
    image: "agency_africa/thumbnails/cdg_capital",
    video: "agency_africa/videos/cdg_capital_lavenir_avec_passion",
    id: "cdgc-apital",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "#EtreEssentiels",
    content: "Film de la marque ELSAN à l'occasion des vœux 2021",
    image: "agency_africa/thumbnails/etre_essentiel_elsan",
    video: "agency_africa/videos/elsan_etre_essentiel_f",
    id: "etre-essentiels",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "Attijariwafa bank",
    content:
      "Interviews et production de vidéo en motion design pour les résultats financiers du groupe bancaire",
    image: "agency_africa/thumbnails/attijariwafa_bank_investor_relation",
    video: "agency_africa/videos/awb_ismail_douiri",
    id: "attijariwafa-bank",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "Saham Group",
    content: "Campagne de marque pour le leader de l'assurance au Maroc",
    image: "agency_africa/thumbnails/saham_essentiel",
    video: "agency_africa/videos/integrated_cristal_saham",
    id: "saham-group",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "Restez chez vous !",
    content: "Spots publicitaires pour la marque de cloud gaming Blacknut",
    image: "agency_africa/thumbnails/blacknut_spot",
    video: "agency_africa/videos/video_v1_web_teletravail",
    id: "restez-chez-vous",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "boom!!!",
    content: "Teasing vidéo de l'offre de Coliving de KleyGroup",
    image: "agency_africa/thumbnails/coliving_kley_group",
    video: "agency_africa/videos/kley_boom",
    id: "boom",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "Groupe CDG",
    content:
      "Vidéo en motion design pour la Caisse de Dépôt et de Gestion du Maroc",
    image: "agency_africa/thumbnails/groupe_cgd_film",
    video: "agency_africa/videos/film_cgd_fr",
    id: "groupe-cdg",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "CMI",
    content:
      "Vidéos en motion design pour le Centre Monétique Interbancaire Marocain",
    image: "agency_africa/thumbnails/cmi_motion",
    video: "agency_africa/videos/cmi_video_institutionnel",
    id: "cmi",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "Saham Group, 20 ans",
    content:
      "Vidéo institutionnelle pour célébrer les 20 ans du leader de l'assurance au Maroc",
    image: "agency_africa/thumbnails/saham_20_ans",
    video: "agency_africa/videos/saham_hd_en_broadcast_141015",
    id: "saham-group-20-ans",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "Alcatel Go Watch",
    content:
      "Campagne publicitaire mondiale pour le lancement de la première montre connectée d'Alcatel",
    image: "agency_africa/thumbnails/alcatel_go_watch",
    video: "agency_africa/videos/alcatel_go_watch_manifesto",
    id: "alcatel-go-watch",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "Ile Seguin-Rives de Seine",
    content:
      "Interviews et prises de vues drone pour l'aménageur Val de Seine Aménagement",
    image: "agency_africa/thumbnails/itw_en_perspective_pont_dayde_0806",
    video: "agency_africa/videos/itw_en_perspective_pont_dayde_0806",
    id: "ile-seguin-rives-de-seine",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "La Belle et La Bête",
    content:
      "Jingle de révélation du Musical de Broadway au théâtre Mogador à Paris",
    image: "agency_africa/thumbnails/la_belle_et_la_bete_mogador",
    video: "agency_africa/videos/teaser_la_belle_et_la_bete",
    id: "la-belle-et-la-bete",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "Elsan",
    content:
      "Motion design pour dévoiler le nouveau nom et logo du premier groupe de santé privé en France",
    image: "agency_africa/thumbnails/elsan_revelation",
    video: "agency_africa/videos/reveal_logo",
    id: "elsan",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "DocCity",
    content:
      "Vidéo en motion design et 3D pour présenter le prochain centre de santé de Marseille",
    image: "agency_africa/thumbnails/doc_city_marseille",
    video: "agency_africa/videos/film_dc_marseillev15_new_voice",
    id: "doc-city",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "Saemes",
    content:
      "Rapport d'activité du leader des solutions de mobilité parisiennes",
    image: "agency_africa/thumbnails/saemes_ra2022",
    video: "agency_africa/videos/saemes_final_4k_02",
    id: "saemes",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
  {
    title: "Lockall",
    content:
      "Vidéo motion design de présentation de la start-up parisienne de self storage",
    image: "agency_africa/thumbnails/lockall_motion",
    video: "agency_africa/videos/lockall_video_services09",
    id: "lockall",
    isAward: false,
    isStrategiesGrandPrix: false,
  },
];
