export const cloudinaryName = "dbzh1g3j0";

export const sliderData = [
  {
    title: "Profil\ndu Groupe",
    linkTitle: "Groupe",
    content:
      "Entretien avec Monsieur Mohamed El Kettani, \n Président Directeur Général du Groupe Attijariwafa bank.",
    delai: "1:55",
    image: "RA AWB/thumbnails/profil-du-groupe",
    imageGifOff: "RA AWB/thumbnails/profil-du-groupe",
    imageGifOn: "RA AWB/thumbnails/rapport_financier-on",
    alt: "image alt",
    video: "RA AWB/Preview-09",
    id: "edito",
    isMultiple: true,
    children: [
      {
        title: "Identité",
        id: "identite",
        delai: "1:55",
        video: "RA AWB/Preview-09",
        color: "#FF9922",
      },
      {
        title: "Stratégie",
        id: "strategie",
        delai: "2:32",
        video: "RA AWB/Preview-02",
        color: "#FF9D2A",
      },
      {
        title: "Gouvernance",
        id: "gouvernance",
        delai: "1:48",
        video: "RA AWB/Preview-03",
        color: "#C0764C",
      },
      {
        title: "Performances",
        id: "performances",
        delai: "3:02",
        video: "RA AWB/Preview-04",
        color: "#FF5C00",
      },
      {
        title: "Distinctions",
        id: "distinctions",
        delai: "2:35",
        video: "RA AWB/Preview-01",
        color: "#FF3D00",
      },
    ],
  },
  {
    title: "UN GROUPE\nRELATIONNEL",
    linkTitle: "Relationnel",
    content:
      "Youssef Rouissi,Directeur Général Délégué, Pôle Corporate & Investment Banking.\nHassan Bertal, Directeur Général Délégué, Pôle Banque de Détail Maroc et Europe.",
    delai: "",
    image: "RA AWB/thumbnails/awb_two_men",
    imageGifOff: "RA AWB/thumbnails/awb_two_men",
    imageGifOn: "RA AWB/thumbnails/excelence_relationnelle-on",
    alt: "image alt",
    video: "",
    id: "excellence_relationnelle",
    isMultiple: true,
    children: [
      {
        title: "Viser l’excellence",
        id: "viser_excellence",
        delai: "3:02",
        video: "RA AWB/Preview-04",
        color: "#FF9922",
      },
      {
        title: "Centricité client",
        id: "centricite_client",
        delai: "2:35",
        video: "RA AWB/Preview-01",
        color: "#FF3D00",
      },
    ],
  },
  {
    title: "UN GROUPE\nINNOVANT",
    linkTitle: "Innovation",
    content:
      "Hassan El Bedraoui, Directeur Général Délégué, Pôle Transformation,\nInnovation, Technologies et Opérations.",
    delai: "1:48",
    image: "RA AWB/thumbnails/innovation_transformation",
    imageGifOff: "RA AWB/thumbnails/innovation_transformation",
    imageGifOn: "RA AWB/thumbnails/innovation_transformation-on",
    alt: "image alt",
    video: "RA AWB/Preview-03",
    id: "innovation_transformation",
    isMultiple: false,
    children: null,
  },
  {
    title: "UN GROUPE\nPANAFRICAIN",
    linkTitle: "Panafricain",
    content:
      "Ismail Douiri, Directeur Général Délégué, Pôle Banque de\nDétail à l’International et Filiales de Financement\nSpécialisées.",
    delai: "3:02",
    image: "RA AWB/thumbnails/group_panafricain",
    imageGifOff: "RA AWB/thumbnails/group_panafricain",
    imageGifOn: "RA AWB/thumbnails/group_panafricain-on",
    alt: "image alt",
    video: "RA AWB/Preview-04",
    id: "groupe_panafricain",
    isMultiple: false,
    children: null,
  },
  {
    title: "UN GROUPE\nCITOYEN",
    linkTitle: "Citoyen",
    content:
      "Mohamed Soussi, Directeur Général Adjoint, en charge du\nCapital Humain.",
    delai: "2:35",
    image: "RA AWB/thumbnails/strategie_developpements",
    imageGifOff: "RA AWB/thumbnails/strategie_developpements",
    imageGifOn: "RA AWB/thumbnails/strategie_developpements-on",
    alt: "image alt",
    video: "RA AWB/Preview-01",
    id: "strategie_developpements",
    isMultiple: false,
    children: null,
  },
];
